# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2482bbb93c19a605c983925f346da0ae874021a5daf691c4cb9af39ddcb315cf19ead19088ddc339610c99bed85c0ef959b69f69f1b3e94977c1d3f62dd15803
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_key: <%= ENV["AWS_ACCESS_KEY_ID"] %>

test:
  secret_key_base: 7faf6ef05014d44f6c2fe4dc7fa2491ffa9196ad6f6e47004ab2d55fdd4f1ab53c67437f134006b000b26e7f323ef0ed0437f09d8113ff180f78ac0baeac8dcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_key: <%= ENV["AWS_ACCESS_KEY_ID"] %>

